### ISSUE TITLE
Paypal payment setting page

### ISSUE THREAD

**Issue by qnguy29** [Peterburnett/QUTCapstone2020#22] opened 2020-08-06 14:16 UTC
Add to page:
- Payment gateway enabled checkbox
- Client ID textbox
- Global course price textbox (floating point value if possible)
- Currency drop down box 
- Color drop down box: [gold, blue, silver, white, black]
- Shape drop down box: [rectangle, pill]

**Comment by harunaka11037** [comment] 2020-08-06 14:25
Closing as this is an accidental duplicate of #23

**Closed as completed** 2020-08-06 14:25 UTC
